{% set name = "tfcausalimpact" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tfcausalimpact-{{ version }}.tar.gz
  sha256: c7b84d9f183e452c04a495ad40810f87bc6070a68fb3f8c0fddf6211dc71ec25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0,<3.12
    - flake8
    - isort
    - pip
  run:
    - python >=3.0,<3.12
    - jinja2
    - pandas >=1.3.5,<=2.2
    - tensorflow >=2.10
    - tensorflow-probability >=0.18,<=0.24
    - matplotlib-base

    # tensorflow-probaility[tf]
    - tf-keras >=2.10

test:
  imports:
    - causalimpact
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/WillianFuks/tfcausalimpact
  summary: Python version of Google's Causal Impact model on top of Tensorflow Probability.
  dev_url: https://github.com/WillianFuks/tfcausalimpact
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
