{% set name = "tfcausalimpact" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tfcausalimpact-{{ version }}.tar.gz
  sha256: 0e362965082377a3518f56b555ede56e4fedefd3f44fd03cd40946470ff75375

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flake8
    - isort
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - jinja2
    - pandas >=1.3.5,<=2.2
    - tensorflow >=2.10
    - tensorflow-probability >=0.18,<=0.25
    - matplotlib-base

    # tensorflow-probaility[tf]
    - tf-keras >=2.10

test:
  imports:
    - causalimpact
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WillianFuks/tfcausalimpact
  summary: Python version of Google's Causal Impact model on top of Tensorflow Probability.
  dev_url: https://github.com/WillianFuks/tfcausalimpact
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
